### ISSUE TITLE
Extend send-log with detailed information in case of send errors

### ISSUE THREAD

**Issue by gadgetto** [gadgetto/GoodNews#50]

**Comment by BakytzhanAkzhol** [comment]
I get in the logs the error. But, I do not see the detailed information about the error. How can I find out why ?
In the status tab to 'send-Log' says "Send error";

**Comment by gadgetto** [comment]
If GoodNews is not sending mails, it could have many reasons:

- first check if test-mails can be sent
- check back with your hosting provider if there are any restrictions for sending mails via PHP
- check the mail servers log
- check the web servers log

**Comment by bogdanof** [comment]
@gadgetto hello,
thanx for GoodNews plugin!
Got issue, when GN is trying to send emails but stacked in the very beginning - I see "sending..." status, and 0 out of 3 recipients processed. Test mailing is working well. Mailing log is empty.
What can be the reason?

**Comment by gadgetto** [comment]
Did you setup have a cron job?

Please read: http://www.bitego.com/extras/goodnews/goodnews-implementation/

**Comment by bogdanof** [comment]
@gadgetto I did't, 
now it's working, thank you!

**Comment by gadgetto** [comment]
Implemented in GoodNews 2.0 (not available for 1.x)
