### ISSUE TITLE
Server protocol in sent mails

### ISSUE THREAD

**Issue by devlanda** [gadgetto/GoodNews#55]
When I send a mailing via GoodNews from a https enabled website, the actual mail does not contain link references to https but to http. For instance the Read it online, Unsubscribe and Edit Mailing Profile links.

Updating the system setting 'server_protocol' from http to https does not change the outcome.
It can be solved with the context setting 'site_url'. However, it would be nice if GoodNews picks up the protocol automatically.

Additional: In the online preview of the mailing the protocol is respected well.

**Comment by gadgetto** [comment]
GoodNews currently is indeed completing URLs only based on `site_url` setting. 

As I wrote this part of code I thought the `site_url` setting is the best way to determine the scheme of the websites URL. In the meantime I learned that `site_url` is a dynamically generated system setting.

Shouldn't be the `site_url`value be updated automatically if you change the `server_protocol`?

**Comment by gadgetto** [comment]
Just found this issue on MODX GitHub page:
https://github.com/modxcms/revolution/issues/13269

Seems that `server_protocol ` does indeed nothing currently and should be removed completely. `site_url` setting is the way to go.

Therefore I won't change GoodNews behavior until the case is closed/fixed on MODX side.
