### ISSUE TITLE
Feature Request: Use utf8mb4_unicode_ci encoding on tables

### ISSUE THREAD

**Issue by digitalpenguin** [gadgetto/GoodNews#68]
Hi! Just trying out your extra for the first time. Great stuff!

In a future version, would it be possible to switch to using utf8mb4_unicode_ci on the database tables as the default?
This way we could have support for languages such as Chinese and Japanese.
Cheers!

**Comment by gadgetto** [comment]
This is definitely a request worth to check! I don't want to exclude countries from use.

I'll have a look at how easy this will be to implement. The problem is when someone is updating and already installed GoodNews version. This could lead to a lot of problems.

**Comment by digitalpenguin** [comment]
Hmm yeah I see what you mean. However, I'm *pretty* sure by default a package upgrade won't change an existing table.
Definitely worth testing first though! :)

**Comment by gadgetto** [comment]
If I'd implement this change I definitely would also upgrade existing installations (this would mean converting existing db tables to utf8mb4_unicode_ci). Otherwise we would get a very fragmented install base and testing and bug fixing could lead to further problems.

**Comment by gadgetto** [comment]
Closing this issue because it's currently not planned to implement utf8mb4_unicode_ci.
