### ISSUE TITLE
Feature Request: Possibility to have subscribers and mails in own custom - tables

### ISSUE THREAD

**Issue by Bruno17** [gadgetto/GoodNews#74]
Would it be possible to have subscribers and mails in custom tables, instead of using users and resources? 
For example, I have an Extra to manage club members, where I need to send mass mails from time to time. All members and newsletters are stored within custom-tables of that package. Currently I'm sending mails within one process, which is very time consuming. I like, how GoodNews handles that, but don't want to have resources for each newsletter and don't want to have a MODX - user for each member.

**Comment by gadgetto** [comment]
This would require a complete rewrite as many features of GoodNews are depending on user objects and their built in methods.

Is there a reason on why you don't like mailings to be resources?

**Comment by Bruno17** [comment]
I see, thanks for the quick response!
I like to keep things seperate and I don't like data, like mailings, to be in the resource-tree for several reasons. 
In my example, I have mailings related to specific dates, for example invite-mailings to events, also there are mailings related to specific member-groups and so far.
Also, sometimes I need to duplicate the whole project, but just the resource-structure without data. That's much simpler, when I have all data within custom-tables and not in the site_content.
And I like to keep the resource-map small.
I think, I will integrate the send-processing directly into my package, then.
