### ISSUE TITLE
Make use of extended fields of the user to filter

### ISSUE THREAD

**Issue by funkyduke** [gadgetto/GoodNews#77]
If possible it would be great to be able to filter on the extended fields of the user inside a usergroup. I have one usergroup but the users speak different languages. So I save an extended field with the user to saye nl, fr or en. I would like to send a newsletter to the nl in Dutch, to fr in French en to en in English. Making extra usergroups would be a solution, but that makes it to complicated for the client. A filter (where statement) would be great for a group.

**Comment by gadgetto** [comment]
GoodNews provides a 2 level categorization (groups, categories). Subscribers can be members of more than one groups/categories.
Wouldn't it be better to additionally put your subscribers in language categories?

e.g.:

Group1
Group2
Languages
-- EN
-- DE
-- FR

**Comment by funkyduke** [comment]
The categorie section doesn't give me the groups. But even then, a manually selection must be done of the users to a categorie? Or do I see this wrong?
![afbeelding](https://user-images.githubusercontent.com/1769979/81424423-3a53b200-9156-11ea-91a3-7cc85d8da143.png)
![afbeelding](https://user-images.githubusercontent.com/1769979/81424512-5e16f800-9156-11ea-8f3a-9177e745fb6c.png)

**Comment by gadgetto** [comment]
When linked to a MODX user group, this GoodNews group cannot be used to manage subscribers!
These special groups should only be used for sending mails to internal MODX user group members (like admins or editors or so).

"normal" groups aren't linked to an internal MODX user group.

**Comment by funkyduke** [comment]
ah ok, but that's where I want to use it for. The client has an internal employee portal and wants to inform their member (who are in usergroups) with internal mailings. That's why I asked about the extended fields, then I can filter on it to send a newsletter in the correct language of the user.

**Comment by gadgetto** [comment]
Currently this will not be implemented as it seems to be an edge case, sorry!

Nothing hinders you to additionally put your internal group members into GoodNews groups/categories too. So you can easily select per language.
