### ISSUE TITLE
Preview doesn't show images

### ISSUE THREAD

**Issue by funkyduke** [gadgetto/GoodNews#78]
The preview inside Modx doesn't show the images inserted with the editor (Redactor v3). If you send a testmail the images are OK in the mail.

**Comment by gadgetto** [comment]
Can't reproduce this. The mail preview uses the same methods as each other MODX resource to render the preview.
Is the preview working in other (none GoodNews) resource documents?
Could you try to test this using the built in editor?

**Comment by funkyduke** [comment]
OK, I forgot the base tag in the template. I think you should also put in sample.GoodNewsNewsletterTemplate1 and sample.GoodNewsNewsletterTemplate2.

**Comment by gadgetto** [comment]
You don’t need the base tag, as GoodNews automatically completes relative URLs to full URLs.

**Comment by funkyduke** [comment]
I think you need it for the preview in Modx, otherwise the image is not showed. Without base url the image was not visible in the preview, with base url it's visible.

**Comment by gadgetto** [comment]
I’m always using root-relative URLs (/path/to/image.jpg). My WYSIWYG editors are configured to work this way.
But using a base tag should also work.

**Comment by funkyduke** [comment]
OK, but maybe it's a good idea to have it in the documentation somewhere.
