### ISSUE TITLE
Send password in email

### ISSUE THREAD

**Issue by funkyduke** [gadgetto/GoodNews#79]
When using GoodNewsSubscription for registration of a new user I would like to send the user a random password just like in the snippet Register. But now the password isn't visible in the email.

`[[+password]]`

I understand that you do this because of security-issues, but I would like the option to send it anyway. For a front-end userplatform the user has to change their password after all, but they need a temporary password to log in.

**Comment by gadgetto** [comment]
Could you please try the following (if it works I can implement this small change in the next release):

- Open file: `/core/components/goodnews/processors/web/subscription.class.php`
- Comment out line 476: `// $properties['cachepwd'],`
- then use the subscription snippet with the param ``&activation=`0` `` - this should allow the placeholder [[+password]] in your templates.

**Comment by funkyduke** [comment]
This works, if you don't forget to set the subscriptionEmailSubject because then the system uses this to send the mail and not the activation-mail.

If you leave activation to 1 and comment out line 476 (not cachepwd but password) then the activation-mail works with the password inside it. I did not test the activationlink.

In mean time I solved it with an own snipped, but of course it would be better if it's build in to have the possibility to send the password (with knowing the risks of doing that).

`$user = $hook->getValue('goodnewssubscription.user');
if ($user == null) { return false; }

// get user
$modx->user =& $user;

// email them the account creation confirmation message
$userdata = array(
    'username' => $hook->getValue('email'),
    'password' => $hook->getValue('password'),
    'fullname' => $hook->getValue('fullname')
);
$msg = $modx->getChunk('ActivateEmailTpl',$userdata);
$modx->user->sendEmail($msg);`

**Comment by gadgetto** [comment]
With the next release [[+password]] placeholder will be allowed in GoodNewsSubscription snippet.

> This works, if you don't forget to set the subscriptionEmailSubject because then the system uses this to send the mail and not the activation-mail.

I don't get you here. Could you please explain more detailed? Another bug?

**Comment by funkyduke** [comment]
No, not a bug. It's just about setting the activation to 0 or 1. If activation is off, the snippet doesn't send the activation mail, but the subscription mail. In that case you can't forget to set the subject or no mail is send.

**Comment by gadgetto** [comment]
If you don't set a subscription email subject, GoodNews should take a default subject from preinstalled lexicon files.

https://github.com/gadgetto/GoodNews/blob/f2c1fedab3a071ea4ec64d2e60e3bbe9cbbed383/core/components/goodnews/model/goodnews/goodnewssubscriptioncontroller.class.php#L734

I tried to duplicate this but in my environment it works as expected.
Could you please post your snippet call?

**Comment by gadgetto** [comment]
Added in latest release!
