### ISSUE TITLE
Cancelbutton gives blank screen in 1.6.0.

### ISSUE THREAD

**Issue by funkyduke** [gadgetto/GoodNews#80]
The cancel button in a mail-resource gives a blank screen.

![afbeelding](https://user-images.githubusercontent.com/1769979/82283366-75e04e80-9996-11ea-8d75-6249ec5d24ec.png)

**Comment by gadgetto** [comment]
Are there any error messages in browser console log?

I see on your screenshot, that you are using a plugin to switch languages. Could you please try to disable this and check if the problem persists?

**Comment by gadgetto** [comment]
Ahh, please clear your browser cache'! I see on the buttons layout that your site is using the old JS resources!
