### ISSUE TITLE
error in manager, goodnews admin

### ISSUE THREAD

**Issue by julienstuder** [gadgetto/GoodNews#83]
in modx 2.8.1 and goodnews 1.6

the paths are wrong when clicking on the parameter icon in goodnews dashboard

it goes to manager/?a=index&action=settings
and display an error : Could not find action file at: controllers/default/index.php

good path (taken from another install) is manager/?a=settings&namespace=goodnews

**Comment by gadgetto** [comment]
I assume you mean the settings icon left/top of the GoodNews interface. But I can't reproduce this. Just tested in a 2.7.1 and 2.8.1 install.
You could clear your browsers cache and hard reload the page and try again?
