### ISSUE TITLE
MODX version compatibility

### ISSUE THREAD

**Issue by SnowCreative** [gadgetto/GoodNews#85]
GoodNews is not listed on the MODX site as compatible with MODX 2.8.x, so your version 1.6.0 does not show up as an update in the MODX manager extras installation screen. I had to download the new version and upload it manually to my sites. It's working fine, so I haven't discovered anything incompatible with MODX 2.8.3. The GoodNews extra on the MODX site is listed as compatible with MODX 2.3 – 2.7.

**Comment by gadgetto** [comment]
Thanks for reporting! Fixed now!
