### ISSUE TITLE
Modx 3

### ISSUE THREAD

**Issue by smartmmm** [gadgetto/GoodNews#86]
Hi, any plans on making GoodNews available for Modx 3? That would be awesome ...

**Comment by gadgetto** [comment]
Yes, this is definitely planned.

**Comment by gadgetto** [comment]
I'm away from MODX for 2 years now and need to setup a new dev environment for MODX 3. After that I'll continue development of GoodNews.

**Comment by smartmmm** [comment]
Great! Thanks so much!

**Comment by glebscore** [comment]
Hi, noticed that the badge shows the minimum MODX version is 3.x. But the official repository shows the opposite:
1.6.1-pl
November 20, 2022
2.3 – 2.8

**Comment by gadgetto** [comment]
You need to use the 1.x branch - this is the official one working for 2.3 up to 2.8. The 2.x branch is currently in development and not ready for use. This is the MODX 3.x only branch!

**Comment by glebscore** [comment]
Got it, thank you!

**Comment by gadgetto** [comment]
Done with new v2.0.0-alpha2
